templates:
  params:
    author-email: dev@veniogames.com
    author-name: Ruud van Asseldonk
    github-username: ruuda

build:
  split-objs: true

package-indices:
  - name: Hackage
    download-prefix: https://s3.amazonaws.com/hackage.fpcomplete.com/package/

    git: https://github.com/commercialhaskell/all-cabal-hashes.git

    # Not using the http one, because it does not support signature verification.
    # http: https://s3.amazonaws.com/hackage.fpcomplete.com/00-index.tar.gz

    # Do verify downloads (this is off by default).
    gpg-verify: true

    # Some packages in Stackage snapshots do not have hashes.
    require-hashes: false
